# Comparisons {.unnumbered}

```{r set}
#| message: false
#| warning: false
library(tidyverse)
ducke <- read_tsv("data/derived_data/ducke_sum.tsv") %>% 
  mutate(scientific = paste(genus, species)) %>% 
  left_join(read_tsv("data/derived_data/cor_tab.tsv")) %>% 
  select(family_cleaned, genus_cleaned, species_cleaned, hand, abundance) %>% 
  filter(!is.na(species_cleaned)) %>% 
   rename_all(~ gsub("_cleaned", "", .)) %>% 
  mutate(scientific = paste(genus, species))
paracou <- read_tsv("data/derived_data/paracou_sum.tsv") %>% 
  mutate(scientific = paste(genus, species)) %>% 
  left_join(read_tsv("data/derived_data/cor_tab.tsv")) %>% 
  select(family_cleaned, genus_cleaned, species_cleaned, hand, abundance) %>% 
  filter(!is.na(species_cleaned)) %>% 
   rename_all(~ gsub("_cleaned", "", .)) %>% 
  mutate(scientific = paste(genus, species))
data <- list(Ducke = ducke, Paracou = paracou) %>% 
  bind_rows(.id = "site") %>% 
  select(-scientific) %>% 
  gather(variable, value, -site, -family, -genus, -species) %>% 
  mutate(variable = paste0(variable, "_", site)) %>% 
  select(-site) %>% 
  group_by(variable, family, genus, species) %>% 
  summarise_all(mean) %>% 
  pivot_wider(names_from = variable, values_from = value) %>% 
  rowwise() %>% 
  mutate(hand_mean = mean(c(hand_Paracou, hand_Ducke), na.rm = TRUE)) %>% 
  mutate(abundance_mean = mean(c(abundance_Paracou, abundance_Ducke), na.rm = TRUE))
```

```{r venn}
#| message: false
#| warning: false
#| fig-cap: Caption.
library(ggvenn)
ggvenn(list(Ducke = ducke$scientific, 
            Paracou = paracou$scientific))
```

```{r abund}
#| message: false
#| warning: false
#| fig-cap: Caption.
data %>% 
  ggplot(aes(abundance_Paracou, abundance_Ducke, col = hand_mean)) +
  geom_abline() +
  geom_smooth(method = "lm", se = FALSE, col = "grey") +
  geom_point() +
  theme_bw() +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_viridis_c() +
  scale_color_viridis_c("Mean\nHAND\n[m]") +
  ggpubr::stat_cor() +
  xlab("Paracou Mean Abundance [N/ha]") +
  ylab("Ducke Mean Abundance [N/ha]")
```

```{r hand}
#| message: false
#| warning: false
#| fig-cap: Caption.
data %>% 
  ggplot(aes(hand_Paracou, hand_Ducke, col = abundance_mean)) +
  geom_abline() +
  geom_smooth(method = "lm", se = FALSE, col = "grey") +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c("Mean\nAbundance\n[N/ha]", trans = "log") +
  ggpubr::stat_cor() +
  xlab("Paracou Mean Height Above Nearest Drainage [HAND, m]") +
  ylab("Ducke Mean HAND [m]") +
  geom_vline(xintercept = 10, linetype = "dashed")
```

```{r venn_hand}
ggvenn(list("Ducke HAND<10" = filter(ducke, hand < 10)$scientific, 
            "Paracou HAND<10" = filter(paracou, hand < 10)$scientific, 
            "Ducke HAND>=10" = filter(ducke, hand >= 10)$scientific, 
            "Paracou HAND>=10" = filter(paracou, hand >= 10)$scientific))
```
