project:
  type: book
  output-dir: docs

book:
  title: "WTD"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - 11_Ducke.qmd
    - 12_Paracou.qmd
    - 13_Species.qmd
    - 14_Comparisons.qmd
  appendices:
    - 91_literature.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
